version: '3.8'

services:
  valuator:
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2
    depends_on:
      - redis
      - nats

  rankcalculator:
    build:
      context: ./microservices/rank-calculator
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2
    depends_on:
      - redis
      - nats

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./microservices/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      - valuator

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  nats:
    image: nats-streaming:0.16.2
    container_name: nats
    restart: on-failure
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./microservices/nats/nats.conf:/etc/nats/nats.conf
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
  redis_data: