version: '3.8'

x-redis-common: &redis-common
  image: redis:latest
  command:
     - redis-server
     - --aclfile /usr/local/etc/redis/users.acl
  healthcheck:
    test: [ "CMD", "redis-cli", "ping" ]
    interval: 10s
    timeout: 5s
    retries: 3
  networks:
    - app-network

services:
  valuator:
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2
    environment:
      REDIS_MAIN_ADR: "redis-main:6379"
      REDIS_EN_ADR: "redis-en:6379"
      REDIS_RU_ADR: "redis-ru:6379"
      REDIS_ASIA_ADR: "redis-asia:6379"
      REDIS_USERNAME: "user1"
      REDIS_PASSWORD: "password1"
    depends_on:
      - redis-main
      - redis-en
      - redis-ru
      - redis-asia
      - nats

  rankcalculator:
    build:
      context: ./microservices/rank-calculator
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2
    environment:
      REDIS_MAIN_ADR: "redis-main:6379"
      REDIS_EN_ADR: "redis-en:6379"
      REDIS_RU_ADR: "redis-ru:6379"
      REDIS_ASIA_ADR: "redis-asia:6379"
      REDIS_USERNAME: "user1"
      REDIS_PASSWORD: "password1"
    depends_on:
      - redis-main
      - redis-en
      - redis-ru
      - redis-asia
      - nats

  authentication:
    build:
      context: ./microservices/authentication
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2
    environment:
      REDIS_MAIN_ADR: "redis-main:6379"
      REDIS_EN_ADR: "redis-en:6379"
      REDIS_RU_ADR: "redis-ru:6379"
      REDIS_ASIA_ADR: "redis-asia:6379"
      REDIS_USERNAME: "user1"
      REDIS_PASSWORD: "password1"

  eventlogger:
    build:
      context: ./microservices/event-logger
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network
    deploy:
      replicas: 1
    depends_on:
      - nats

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./microservices/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      - valuator

  redis-main:
    <<: *redis-common
    container_name: redis-main
    volumes:
      - redis_data:/data
      - ./microservices/redis/users.acl:/usr/local/etc/redis/users.acl

  redis-ru:
    <<: *redis-common
    container_name: redis-ru
    volumes:
      - redis_ru_data:/data
      - ./microservices/redis/users.acl:/usr/local/etc/redis/users.acl

  redis-en:
    <<: *redis-common
    container_name: redis-en
    volumes:
      - redis_en_data:/data
      - ./microservices/redis/users.acl:/usr/local/etc/redis/users.acl

  redis-asia:
    <<: *redis-common
    container_name: redis-asia
    volumes:
      - redis_asia_data:/data
      - ./microservices/redis/users.acl:/usr/local/etc/redis/users.acl

  nats:
    image: nats-streaming:0.16.2
    container_name: nats
    restart: on-failure
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./microservices/nats/nats.conf:/etc/nats/nats.conf
    networks:
      - app-network

  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    restart: always
    environment:
      - CENTRIFUGO_ADMIN_PASSWORD=admin
      - CENTRIFUGO_ADMIN_SECRET=admin
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./microservices/centrifugo/config.json:/centrifugo/config.json
    ports:
      - "8000:8000"
      - "3000:3000"

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis-main
      - redis-ru
      - redis-en
      - redis-asia
    volumes:
      - redis-insight:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
  redis_data:
  redis_ru_data:
  redis_en_data:
  redis_asia_data:
  redis-insight:
