version: '3.8'

services:
  valuator1:
    container_name: valuator1
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - redis

  valuator2:
    container_name: valuator2
    build:
      context: ./microservices/valuator
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./microservices/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8082:8082"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      - valuator1
      - valuator2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
  redis_data: