worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream valuator {
        server valuator:8082;
    }

    upstream rankcalculator {
        server rankcalculator:8082;
    }

    server {
        listen 8080;
        server_name localhost;

        location ~ /rankcalculator {
            proxy_pass http://rankcalculator;
        }

        location ~ /valuator {
            proxy_pass http://valuator;
        }

        location ~ / {
            proxy_pass http://valuator/valuator$request_uri;
        }
    }
}